make project open to contributions

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -12,9 +12,6 @@ jobs:
   build:
     runs-on: ubuntu-latest
 
-    env:
-      VITE_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -27,5 +24,32 @@ jobs:
       - name: Install dependencies
         run: npm install
 
+      - name: Lint code
+        run: npm run lint
+
       - name: Build app
         run: npm run build
+    
+      - name: Check for Lint/Build Errors
+        if: failure()
+        run: |
+          if [ -s "$(git diff --name-only ${{ github.sha }} ${{ github.event.before }})" ]; then
+            echo "Linting or build errors detected."
+            curl -X POST \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
+              -d '{"body": "Linting or build errors detected. Please review and address the issues before merging."}'
+            exit 1
+          fi
+      - name: If No Errors, Merge
+        if: success()
+        run: |
+          if [ -z "$(git diff --name-only ${{ github.sha }} ${{ github.event.before }})" ]; then
+            echo "No linting or build errors detected. Merging."
+            curl -X PUT \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/merge \
+              -d '{"commit_title": "You Rock  Thank you for your contribution! One core maintainer will review your changes and merge them if they are approved."}'
+          fi
